# Generated by Django 4.1.7 on 2023-04-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Air',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_name', models.CharField(max_length=250, null=True)),
                ('airfrom', models.CharField(max_length=250, null=True)),
                ('airto', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=250, null=True)),
                ('busfrom', models.CharField(max_length=250, null=True)),
                ('busto', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=250, null=True)),
                ('tfrom', models.CharField(max_length=250, null=True)),
                ('tto', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
