# Generated by Django 4.1.7 on 2023-04-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='air',
            name='AirEstimation',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='busEstimation',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='tEstimation',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
