# Generated by Django 4.1.7 on 2023-04-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_air_airestimation_bus_busestimation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='air',
            name='airDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='busDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='tDate',
            field=models.DateTimeField(null=True),
        ),
    ]
