# Generated by Django 4.1.7 on 2023-04-18 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_air_airdate_alter_bus_busdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='air',
            name='airDate',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='busDate',
        ),
        migrations.RemoveField(
            model_name='train',
            name='tDate',
        ),
    ]
