# Generated by Django 4.1.7 on 2023-04-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_remove_air_airdate_remove_bus_busdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='busdate',
            field=models.DateField(null=True),
        ),
    ]
