# Generated by Django 4.1.7 on 2023-04-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_bus_busdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='air',
            name='airdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='traindate',
            field=models.DateField(null=True),
        ),
    ]
