# Generated by Django 4.1.7 on 2023-04-18 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_air_airdate_train_traindate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bususer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('businfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.bus')),
            ],
        ),
    ]
