# Generated by Django 4.1.7 on 2023-04-18 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_bususer'),
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bususer',
            name='businfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.bus'),
        ),
        migrations.AlterField(
            model_name='bususer',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.userinfo'),
        ),
    ]
