# Generated by Django 4.1.7 on 2023-04-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_bus_total_seats_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='number',
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_number',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
