# Generated by Django 4.1.7 on 2023-04-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_remove_seat_bus_remove_seat_number_seat_seat_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('booked_by', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
