# Generated by Django 4.1.7 on 2023-04-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_seatbooking_delete_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=2, null=True)),
                ('is_booked', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='SeatBooking',
        ),
    ]
