# Generated by Django 4.1.7 on 2023-04-21 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_seat_delete_seatbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='bus_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.bus'),
        ),
    ]
