# Generated by Django 4.1.7 on 2023-04-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_seat_bus_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='bus_name',
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.IntegerField(null=True),
        ),
    ]
