# Generated by Django 4.1.7 on 2023-04-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_alter_seat_seat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.IntegerField(null=True),
        ),
    ]
