# Generated by Django 4.1.7 on 2023-04-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0019_bus_bus_id_seat_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='bus_identi',
            field=models.CharField(max_length=22, null=True),
        ),
    ]
