# Generated by Django 4.1.7 on 2023-04-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0021_remove_seat_bus_identi'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='t_class',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
