# Generated by Django 4.1.7 on 2023-04-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0022_train_t_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='train_id',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
