# Generated by Django 4.1.7 on 2023-04-24 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0023_train_train_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainseat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=22, null=True)),
                ('is_booked', models.BooleanField(default=False)),
                ('train', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.train')),
            ],
        ),
    ]
