# Generated by Django 4.1.7 on 2023-04-25 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0028_seat_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='air',
            name='air_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='Planeseat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=22, null=True)),
                ('is_booked', models.BooleanField(default=False)),
                ('plane', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.train')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
