# Generated by Django 4.1.7 on 2023-04-25 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0031_bus_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus_payment',
            name='seat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.seat'),
        ),
    ]
