# Generated by Django 4.1.7 on 2023-04-27 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0033_bus_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='tfare',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='train_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid', models.CharField(max_length=22, null=True)),
                ('gender', models.CharField(max_length=22, null=True)),
                ('pay_method', models.CharField(max_length=22, null=True)),
                ('number', models.CharField(max_length=22, null=True)),
                ('seat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.trainseat')),
                ('train', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.train')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
