# Generated by Django 4.1.7 on 2023-04-27 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0034_train_tfare_train_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='air',
            name='afair',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='air_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid', models.CharField(max_length=22, null=True)),
                ('gender', models.CharField(max_length=22, null=True)),
                ('pay_method', models.CharField(max_length=22, null=True)),
                ('number', models.CharField(max_length=22, null=True)),
                ('air', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.air')),
                ('seat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.planeseat')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
